import type { Shipment } from "./types"

export const shipments: Shipment[] = [
  {
    id: "SHP-2024-001",
    origin: "Los Angeles, CA",
    originAddress: "1200 W Olympic Blvd, Los Angeles, CA 90015",
    destination: "New York, NY",
    destinationAddress: "350 5th Ave, New York, NY 10118",
    status: "In Transit",
    carrier: "FedEx Ground",
    weight: "2,450 lbs",
    eta: "Jan 15, 2026",
    priority: "High",
    cost: "$3,450.00",
    customer: "Acme Corporation",
    shipDate: "Jan 10, 2026",
    distance: "2,789",
    trackingNumber: "TRK789456123",
    containerType: "20ft Standard",
    serviceType: "Express Freight",
    contact: {
      email: "logistics@acme.com",
      phone: "+1 (555) 123-4567",
    },
    trackingHistory: [
      {
        status: "Out for delivery",
        location: "Newark, NJ Distribution Center",
        timestamp: "Jan 14, 2026 08:45 AM",
      },
      {
        status: "In transit",
        location: "Philadelphia, PA Hub",
        timestamp: "Jan 13, 2026 02:30 PM",
      },
      {
        status: "Departed facility",
        location: "Chicago, IL Sorting Center",
        timestamp: "Jan 12, 2026 11:20 AM",
      },
      {
        status: "Arrived at facility",
        location: "Denver, CO Hub",
        timestamp: "Jan 11, 2026 06:15 PM",
      },
      {
        status: "Picked up",
        location: "Los Angeles, CA",
        timestamp: "Jan 10, 2026 09:00 AM",
      },
    ],
  },
  {
    id: "SHP-2024-002",
    origin: "Chicago, IL",
    originAddress: "233 S Wacker Dr, Chicago, IL 60606",
    destination: "Miami, FL",
    destinationAddress: "100 SE 2nd St, Miami, FL 33131",
    status: "Delivered",
    carrier: "UPS Freight",
    weight: "1,890 lbs",
    eta: "Jan 12, 2026",
    priority: "Medium",
    cost: "$2,150.00",
    customer: "Global Logistics Inc",
    shipDate: "Jan 8, 2026",
    distance: "1,378",
    trackingNumber: "TRK456789321",
    containerType: "40ft High Cube",
    serviceType: "Standard Ground",
    contact: {
      email: "shipping@globallog.com",
      phone: "+1 (555) 234-5678",
    },
    trackingHistory: [
      {
        status: "Delivered",
        location: "Miami, FL",
        timestamp: "Jan 12, 2026 03:15 PM",
      },
      {
        status: "Out for delivery",
        location: "Miami, FL Distribution Center",
        timestamp: "Jan 12, 2026 07:30 AM",
      },
      {
        status: "In transit",
        location: "Jacksonville, FL Hub",
        timestamp: "Jan 11, 2026 04:20 PM",
      },
      {
        status: "Departed facility",
        location: "Atlanta, GA Sorting Center",
        timestamp: "Jan 10, 2026 10:45 AM",
      },
      {
        status: "Picked up",
        location: "Chicago, IL",
        timestamp: "Jan 8, 2026 08:30 AM",
      },
    ],
  },
  {
    id: "SHP-2024-003",
    origin: "Seattle, WA",
    originAddress: "400 Broad St, Seattle, WA 98109",
    destination: "Boston, MA",
    destinationAddress: "1 Congress St, Boston, MA 02114",
    status: "Pending",
    carrier: "DHL Express",
    weight: "3,200 lbs",
    eta: "Jan 18, 2026",
    priority: "Low",
    cost: "$4,890.00",
    customer: "TechStart Solutions",
    shipDate: "Jan 14, 2026",
    distance: "2,496",
    trackingNumber: "TRK123654789",
    containerType: "20ft Refrigerated",
    serviceType: "Temperature Controlled",
    contact: {
      email: "ops@techstart.com",
      phone: "+1 (555) 345-6789",
    },
    trackingHistory: [
      {
        status: "Pending pickup",
        location: "Seattle, WA Warehouse",
        timestamp: "Jan 14, 2026 10:00 AM",
      },
      {
        status: "Order received",
        location: "Seattle, WA",
        timestamp: "Jan 13, 2026 02:30 PM",
      },
    ],
  },
  {
    id: "SHP-2024-004",
    origin: "Houston, TX",
    originAddress: "1600 Smith St, Houston, TX 77002",
    destination: "Phoenix, AZ",
    destinationAddress: "201 N Central Ave, Phoenix, AZ 85004",
    status: "In Transit",
    carrier: "XPO Logistics",
    weight: "1,650 lbs",
    eta: "Jan 16, 2026",
    priority: "High",
    cost: "$1,950.00",
    customer: "Southwest Distributors",
    shipDate: "Jan 11, 2026",
    distance: "1,178",
    trackingNumber: "TRK987321654",
    containerType: "20ft Standard",
    serviceType: "Express Freight",
    contact: {
      email: "contact@swdist.com",
      phone: "+1 (555) 456-7890",
    },
    trackingHistory: [
      {
        status: "In transit",
        location: "El Paso, TX Hub",
        timestamp: "Jan 14, 2026 01:20 PM",
      },
      {
        status: "Departed facility",
        location: "San Antonio, TX Sorting Center",
        timestamp: "Jan 13, 2026 09:45 AM",
      },
      {
        status: "Picked up",
        location: "Houston, TX",
        timestamp: "Jan 11, 2026 07:15 AM",
      },
    ],
  },
  {
    id: "SHP-2024-005",
    origin: "Atlanta, GA",
    originAddress: "241 Peachtree St NE, Atlanta, GA 30303",
    destination: "Denver, CO",
    destinationAddress: "1801 California St, Denver, CO 80202",
    status: "Delayed",
    carrier: "Old Dominion",
    weight: "2,100 lbs",
    eta: "Jan 19, 2026",
    priority: "Medium",
    cost: "$2,780.00",
    customer: "Mountain Supply Co",
    shipDate: "Jan 9, 2026",
    distance: "1,398",
    trackingNumber: "TRK654987321",
    containerType: "40ft Standard",
    serviceType: "Standard Ground",
    contact: {
      email: "shipping@mountsupply.com",
      phone: "+1 (555) 567-8901",
    },
    trackingHistory: [
      {
        status: "Delayed - Weather conditions",
        location: "Kansas City, MO Hub",
        timestamp: "Jan 14, 2026 11:30 AM",
      },
      {
        status: "In transit",
        location: "St. Louis, MO Sorting Center",
        timestamp: "Jan 12, 2026 03:45 PM",
      },
      {
        status: "Departed facility",
        location: "Nashville, TN Hub",
        timestamp: "Jan 10, 2026 08:20 AM",
      },
      {
        status: "Picked up",
        location: "Atlanta, GA",
        timestamp: "Jan 9, 2026 10:00 AM",
      },
    ],
  },
  {
    id: "SHP-2024-006",
    origin: "Portland, OR",
    originAddress: "1000 SW Broadway, Portland, OR 97205",
    destination: "Austin, TX",
    destinationAddress: "301 Congress Ave, Austin, TX 78701",
    status: "In Transit",
    carrier: "Estes Express",
    weight: "1,425 lbs",
    eta: "Jan 17, 2026",
    priority: "Low",
    cost: "$2,340.00",
    customer: "Lone Star Trading",
    shipDate: "Jan 12, 2026",
    distance: "1,985",
    trackingNumber: "TRK321789456",
    containerType: "20ft Standard",
    serviceType: "Economy Freight",
    contact: {
      email: "logistics@lonestartrading.com",
      phone: "+1 (555) 678-9012",
    },
    trackingHistory: [
      {
        status: "In transit",
        location: "Albuquerque, NM Hub",
        timestamp: "Jan 14, 2026 09:15 AM",
      },
      {
        status: "Departed facility",
        location: "Salt Lake City, UT Sorting Center",
        timestamp: "Jan 13, 2026 05:30 PM",
      },
      {
        status: "Picked up",
        location: "Portland, OR",
        timestamp: "Jan 12, 2026 08:45 AM",
      },
    ],
  },
  {
    id: "SHP-2024-007",
    origin: "Dallas, TX",
    originAddress: "1201 Elm St, Dallas, TX 75270",
    destination: "San Francisco, CA",
    destinationAddress: "345 California St, San Francisco, CA 94104",
    status: "Delivered",
    carrier: "R+L Carriers",
    weight: "2,890 lbs",
    eta: "Jan 13, 2026",
    priority: "High",
    cost: "$3,670.00",
    customer: "Pacific Rim Imports",
    shipDate: "Jan 7, 2026",
    distance: "1,732",
    trackingNumber: "TRK789123456",
    containerType: "40ft High Cube",
    serviceType: "Guaranteed Delivery",
    contact: {
      email: "receiving@pacificrim.com",
      phone: "+1 (555) 789-0123",
    },
    trackingHistory: [
      {
        status: "Delivered",
        location: "San Francisco, CA",
        timestamp: "Jan 13, 2026 01:45 PM",
      },
      {
        status: "Out for delivery",
        location: "Oakland, CA Distribution Center",
        timestamp: "Jan 13, 2026 06:30 AM",
      },
      {
        status: "In transit",
        location: "Sacramento, CA Hub",
        timestamp: "Jan 12, 2026 11:20 AM",
      },
      {
        status: "Departed facility",
        location: "Las Vegas, NV Sorting Center",
        timestamp: "Jan 11, 2026 02:15 PM",
      },
      {
        status: "In transit",
        location: "Phoenix, AZ Hub",
        timestamp: "Jan 9, 2026 04:30 PM",
      },
      {
        status: "Picked up",
        location: "Dallas, TX",
        timestamp: "Jan 7, 2026 09:15 AM",
      },
    ],
  },
  {
    id: "SHP-2024-008",
    origin: "Philadelphia, PA",
    originAddress: "1600 Market St, Philadelphia, PA 19103",
    destination: "Las Vegas, NV",
    destinationAddress: "3799 S Las Vegas Blvd, Las Vegas, NV 89109",
    status: "In Transit",
    carrier: "YRC Freight",
    weight: "1,760 lbs",
    eta: "Jan 20, 2026",
    priority: "Medium",
    cost: "$2,990.00",
    customer: "Desert Wholesale",
    shipDate: "Jan 13, 2026",
    distance: "2,567",
    trackingNumber: "TRK456321789",
    containerType: "20ft Standard",
    serviceType: "Standard Ground",
    contact: {
      email: "orders@desertwholesale.com",
      phone: "+1 (555) 890-1234",
    },
    trackingHistory: [
      {
        status: "In transit",
        location: "Denver, CO Hub",
        timestamp: "Jan 14, 2026 07:50 AM",
      },
      {
        status: "Departed facility",
        location: "Indianapolis, IN Sorting Center",
        timestamp: "Jan 13, 2026 11:45 PM",
      },
      {
        status: "Picked up",
        location: "Philadelphia, PA",
        timestamp: "Jan 13, 2026 10:30 AM",
      },
    ],
  },
]
